# pull official base image
FROM node:20.5.1

COPY ./symptom-tracker /symptom-tracker

# set working directory
WORKDIR /symptom-tracker

# add `/app/node_modules/.bin` to $PATH
ENV PATH /symptom-tracker/node_modules/.bin:$PATH

# install app dependencies
# COPY package.json ./
# COPY package-lock.json ./
# RUN npm update
RUN npm install --silent
# RUN npm install react-scripts@3.4.1 -g --silent

# add app
# COPY . ./

# start app
# CMD ["npm", "start"]
# CMD ["dev", "-f", "tail", "null"]