# pull official base image
FROM node:20.5.1
COPY ./symptom-tracker /symptom-tracker

# set working directory
WORKDIR /symptom-tracker
ENV PATH /symptom-tracker/node_modules/.bin:$PATH
RUN npm install --silent
CMD ["npm", "start"]
# CMD ["dev", "-f", "tail", "null"]