apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jmckeeota/symptom_tracker_backend
        ports:
        - containerPort: 8432
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db_user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: db_password
        - name: ENGINE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: engine
        - name: CONNECTION
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-url
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: database
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8432
      targetPort: 8432
      nodePort: 30002