version: "3.8"
services:
  frontend:
    build: ./frontend
    # depends_on:
    #   - backend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/symptom-tracker:/symptom-tracker
    command: ["npm", "start"]
    # command: ["tail", "-f", "/dev/null"]
  
  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8432:8432
    volumes:
      - ./backend:/api
    environment:
      ENGINE: postgresql
      DATABASE: tracker
      USER: admin
      PASSWORD: admin
      CONNECTION: db

  db: 
    image: postgres:alpine3.17
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: tracker
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tracker"]
      interval: 100s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

